In [2]:
import MDAnalysis 
import pytim
from   pytim.datafiles import *




# Basis example

In [3]:
# load an example configuration file
u         = MDAnalysis.Universe(WATER_GRO)

# initialize the interface, this has to be called only once
# before iterating over the trajectory!
interface = pytim.ITIM(u, max_layers=4)

# write a pdb with the information on the surface layers
interface.writepdb('layers.pdb',centered='middle')

# access the atoms in the layers as an MDAnalysis' AtomGroups
upper_layer = interface.layers[0,0]


print(upper_layer.resids)

/home/glebreton/.local/lib/python3.7/site-packages/MDAnalysis/topology/base.py:203: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  residx = np.zeros_like(criteria[0], dtype=np.int)


[   5    5    5   14   14   14   56   56   56   78   78   78   86   86
   86  106  106  106  125  125  125  137  137  137  151  151  151  187
  187  187  196  196  196  197  197  197  211  211  211  217  217  217
  226  226  226  254  254  254  256  256  256  257  257  257  271  271
  271  275  275  275  278  278  278  285  285  285  301  301  301  312
  312  312  318  318  318  362  362  362  363  363  363  373  373  373
  386  386  386  393  393  393  394  394  394  402  402  402  449  449
  449  473  473  473  494  494  494  521  521  521  559  559  559  577
  577  577  594  594  594  596  596  596  607  607  607  615  615  615
  650  650  650  657  657  657  710  710  710  715  715  715  750  750
  750  765  765  765  779  779  779  797  797  797  801  801  801  807
  807  807  810  810  810  812  812  812  817  817  817  819  819  819
  826  826  826  833  833  833  844  844  844  846  846  846  879  879
  879  906  906  906  925  925  925  950  950  950  951  951  951  970
  970 

# More complexe one

In [6]:
directory = '/data/glebreton/Documents/Encadrement/Stage/2019-2020/Fichier_thibault/MD/2D_40/'

# load an example configuration file
u = MDAnalysis.Universe(directory + 'first_equi.data')
#print(u.residues[0].atoms.types)
#print(u.residues[1260].atoms.types)

u.add_TopologyAttr('names')
u.add_TopologyAttr('types')
u.add_TopologyAttr('radii')
u.add_TopologyAttr('resnames')

for i in range(0, 1200, 1):
    u.residues[i].atoms.names = ['Oabcdefg, 'H', 'H']
    u.residues[i].atoms.types = ['O123456789', 'H', 'H']
    u.residues[i].atoms.radii = [0.8, 0.71, 0.72]
    u.select_atoms('resid ' + str(i)).residues.resnames = 'Wat'
    
for i in range(1200, 2000, 1):
    u.residues[i].atoms.names = ['O', 'H', 'C', 'H', 'H', 'H']
    u.residues[i].atoms.types = ['O', 'H', 'C', 'H', 'H', 'H']
    u.residues[i].atoms.radii = [1.4, 1.6, 1.1, 1.41, 1.45, 1.46]
    u.select_atoms('resid ' + str(i)).residues.resnames = 'Met'

#with MDAnalysis.coordinates.LAMMPS.DATAWriter('my_topology.data') as Towrite:
#    Towrite.write(u)
print('before 1')
print(u.residues[0].atoms.radii)
print(u.residues[1979].atoms.radii)

interface = pytim.ITIM(u, max_layers=4, warnings=True)
upper_layer = interface.layers[0,1]
print(upper_layer.resids)
interface.writepdb('layers_1.pdb',centered='middle')

print('after 1')
print(u.residues[0].atoms.radii)
print(u.residues[1979].atoms.radii)

for i in range(0, 1200, 1):
    u.residues[i].atoms.names = ['Oabcdefg', 'H', 'H']
    u.residues[i].atoms.types = ['O123456789', 'H', 'H']
    u.residues[i].atoms.radii = [2., 0.0, 0.0]
    
for i in range(1200, 2000, 1):
    u.residues[i].atoms.names = ['O', 'H', 'C', 'H', 'H', 'H']
    u.residues[i].atoms.types = ['O', 'H', 'C', 'H', 'H', 'H']
    u.residues[i].atoms.radii = [3.0, 0.0, 3.0, 1.5, 1.5, 1.5]

print('before 2')
print(u.residues[0].atoms.radii)
print(u.residues[1979].atoms.radii)

interface = pytim.ITIM(u, max_layers=4, warnings=True)
upper_layer = interface.layers[0,1]
print(upper_layer.resids)
interface.writepdb('layers_2.pdb',centered='middle')

print('after 2')
print(u.residues[0].atoms.radii)
print(u.residues[1979].atoms.radii)
    

/home/glebreton/.local/lib/python3.7/site-packages/MDAnalysis/core/selection.py:675: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  mask = np.zeros(len(vals), dtype=np.bool)


before 1
[0.8  0.71 0.72]
[1.4  1.6  1.1  1.41 1.45 1.46]
[  20   20   20   23   23   23   30   30   30   87   87   87   88   88
   88  116  116  116  142  142  142  160  160  160  179  179  179  184
  184  184  203  203  203  209  209  209  222  222  222  240  240  240
  245  245  245  265  265  265  268  268  268  300  300  300  345  345
  345  361  361  361  413  413  413  448  448  448  483  483  483  484
  484  484  501  501  501  523  523  523  554  554  554  593  593  593
  616  616  616  626  626  626  666  666  666  704  704  704  756  756
  756  790  790  790  842  842  842  897  897  897  900  900  900  933
  933  933  942  942  942  946  946  946  976  976  976 1013 1013 1013
 1036 1036 1036 1039 1039 1039 1067 1067 1067 1079 1079 1079 1093 1093
 1093 1095 1095 1095 1120 1120 1120 1126 1126 1126 1163 1163 1163 1183
 1183 1183 1191 1191 1191 1207 1207 1207 1207 1207 1207 1213 1213 1213
 1213 1213 1213 1215 1215 1215 1215 1215 1215 1278 1278 1278 1278 1278
 1278 1299 1299 129

In [14]:
directory = '/data/glebreton/Documents/Encadrement/Stage/2019-2020/Fichier_thibault/MD/2D_40/'
# load an example configuration file
u = MDAnalysis.Universe(directory + 'first_equi.data')
#print(u.residues[0].atoms.types)
#print(u.residues[1260].atoms.types)

#u.add_TopologyAttr('names')
u.add_TopologyAttr('radii')

for i in range(0, 1200, 1):
    #u.residues[i].atoms.names = ['Oabcdefg', 'H', 'H']
    u.residues[i].atoms.radii = [0.8, 0.71, 0.72]
    
for i in range(1200, 2000, 1):
#    u.residues[i].atoms.names = ['O', 'H', 'C', 'H', 'H', 'H']
    u.residues[i].atoms.radii = [1.4, 1.6, 1.1, 1.41, 1.45, 1.46]

#with MDAnalysis.coordinates.LAMMPS.DATAWriter('my_topology.data') as Towrite:
#    Towrite.write(u)

with MDAnalysis.coordinates.PQR.PQRWriter('my_topology.pqr') as Towrite:
    Towrite.write(u)


/home/glebreton/.local/lib/python3.7/site-packages/MDAnalysis/coordinates/PQR.py:294: UserWarning: Supplied AtomGroup was missing the following attributes: names, resnames. These will be written with default values. 
  "".format(miss=', '.join(missing_topology)))


In [15]:
import pytim
import MDAnalysis 

u = MDAnalysis.Universe('my_topology.pqr', '/data/glebreton/Documents/Encadrement/Stage/2019-2020/Fichier_thibault/MD/2D_40/first_equi.data')

print(u.residues[0].atoms.types, u.residues[0].atoms.names, u.residues[0].atoms.radii)
print(u.residues[1979].atoms.radii)

interface = pytim.ITIM(u, max_layers=4, warnings=True)

#pytim.ITIM(u, radii_dict={'O':1.14})
#interface = pytim.ITIM(u, max_layers=4,  warnings=True)


print(u.residues[0].atoms.radii)
print(u.residues[1979].atoms.radii)

['X' 'X' 'X'] ['X' 'X' 'X'] [0.80000001 0.70999998 0.72000003]
[1.39999998 1.60000002 1.10000002 1.40999997 1.45000005 1.46000004]


/home/glebreton/.local/lib/python3.7/site-packages/MDAnalysis/topology/base.py:203: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  residx = np.zeros_like(criteria[0], dtype=np.int)


[0.80000001 0.70999998 0.72000003]
[1.39999998 1.60000002 1.10000002 1.40999997 1.45000005 1.46000004]


In [42]:
mydict    = {'O':1.14 , 'H':0.0 , 'C':1.5 , 'H':0.0 , 'H':1.6 , 'H':0.0} # where 'H' refers to the type
interface = pytim.ITIM(u, max_layers=4, radii_dict=mydict, warnings=True)



# Print the layer number

In [25]:
import pytim
import MDAnalysis 

directory = '/home/glebreton/Software/Frog/Doc/Tutorial_files/Traj/Tuto_get_strated/'
u = MDAnalysis.Universe(directory + 'system.data', directory + 'traj_get_strated.dcd')

# u.add_TopologyAttr('names')
u.add_TopologyAttr('radii')

for i in range(0, len(u.residues[:]), 1):
    #u.residues[i].atoms.names = ['O', 'H', 'H']
    u.residues[i].atoms.types = ['O', 'H', 'H']
    u.residues[i].atoms.radii = [0.8, 0.71, 0.72]
    
print(u.residues[0].atoms.types, u.residues[0].atoms.radii)
#print(u.residues[1979].atoms.radii)

nbr_layer = 5
interface = pytim.ITIM(u, max_layers=nbr_layer, warnings=True)


for k in range(0, nbr_layer, 1):
    upper_layer = interface.layers[0,k]
    print(upper_layer.resids)
    iii = 0
    while iii < len(upper_layer.resids):
        nbr_resid = upper_layer.resids[iii]
        print(nbr_resid)
        while nbr_resid == upper_layer.resids[iii] and iii < len(upper_layer.resids):
            iii += 1
            

['O' 'H' 'H'] [0.8  0.71 0.72]
[  12   12   12   13   13   13   16   16   16   17   17   17   49   49
   49   62   62   62  101  101  101  112  112  112  115  115  115  116
  116  116  118  118  118  119  119  119  127  127  127  150  150  150
  168  168  168  170  170  170  184  184  184  185  185  185  198  198
  198  201  201  201  202  202  202  204  204  204  236  236  236  237
  237  237  255  255  255  272  272  272  278  278  278  320  320  320
  323  323  323  353  353  353  367  367  367  368  368  368  371  371
  371  372  372  372  386  386  386  388  388  388  390  390  390  401
  401  401  406  406  406  407  407  407  419  419  419  420  420  420
  422  422  422  437  437  437  447  447  447  474  474  474  491  491
  491  502  502  502  520  520  520  527  527  527  538  538  538  541
  541  541  542  542  542  575  575  575  578  578  578  595  595  595
  625  625  625  629  629  629  639  639  639  640  640  640  662  662
  662  663  663  663  680  680  680  711  711 

IndexError: index 486 is out of bounds for axis 0 with size 486

In [26]:
for i in range(0, len(u.residues[:]), 1):
    print('resid', i, 'layer', u.residues[i].atoms.layers[0], 'side', u.residues[i].atoms.sides[0])

resid 0 layer -1 side -1
resid 1 layer 4 side 0
resid 2 layer -1 side -1
resid 3 layer 1 side 1
resid 4 layer 4 side 1
resid 5 layer -1 side -1
resid 6 layer 4 side 1
resid 7 layer 5 side 0
resid 8 layer 3 side 0
resid 9 layer -1 side -1
resid 10 layer 3 side 0
resid 11 layer 1 side 0
resid 12 layer 1 side 0
resid 13 layer 2 side 0
resid 14 layer 2 side 0
resid 15 layer 1 side 0
resid 16 layer 1 side 0
resid 17 layer 1 side 1
resid 18 layer -1 side -1
resid 19 layer 1 side 1
resid 20 layer 1 side 1
resid 21 layer 2 side 1
resid 22 layer 3 side 1
resid 23 layer 5 side 1
resid 24 layer 4 side 1
resid 25 layer -1 side -1
resid 26 layer 4 side 1
resid 27 layer -1 side -1
resid 28 layer 5 side 0
resid 29 layer 5 side 0
resid 30 layer 2 side 0
resid 31 layer -1 side -1
resid 32 layer 4 side 0
resid 33 layer 4 side 0
resid 34 layer 1 side 1
resid 35 layer 5 side 1
resid 36 layer 4 side 1
resid 37 layer 4 side 1
resid 38 layer 5 side 0
resid 39 layer -1 side -1
resid 40 layer -1 side -1
resid 

resid 572 layer 2 side 0
resid 573 layer 5 side 0
resid 574 layer 1 side 0
resid 575 layer 2 side 0
resid 576 layer 2 side 0
resid 577 layer 1 side 0
resid 578 layer 2 side 1
resid 579 layer 2 side 1
resid 580 layer 4 side 0
resid 581 layer 2 side 1
resid 582 layer 1 side 1
resid 583 layer -1 side -1
resid 584 layer 3 side 1
resid 585 layer 5 side 0
resid 586 layer 4 side 1
resid 587 layer 4 side 0
resid 588 layer 4 side 1
resid 589 layer 3 side 1
resid 590 layer -1 side -1
resid 591 layer -1 side -1
resid 592 layer 4 side 0
resid 593 layer 2 side 0
resid 594 layer 1 side 0
resid 595 layer 2 side 1
resid 596 layer 1 side 1
resid 597 layer 4 side 1
resid 598 layer 1 side 1
resid 599 layer 2 side 1
resid 600 layer -1 side -1
resid 601 layer 4 side 1
resid 602 layer -1 side -1
resid 603 layer -1 side -1
resid 604 layer -1 side -1
resid 605 layer 4 side 1
resid 606 layer 5 side 0
resid 607 layer 4 side 0
resid 608 layer 2 side 0
resid 609 layer 2 side 0
resid 610 layer 3 side 0
resid 611 l

resid 1155 layer 1 side 0
resid 1156 layer -1 side -1
resid 1157 layer -1 side -1
resid 1158 layer -1 side -1
resid 1159 layer 2 side 1
resid 1160 layer 1 side 1
resid 1161 layer 1 side 0
resid 1162 layer 4 side 1
resid 1163 layer -1 side -1
resid 1164 layer 3 side 0
resid 1165 layer 2 side 1
resid 1166 layer 2 side 1
resid 1167 layer -1 side -1
resid 1168 layer 4 side 0
resid 1169 layer 3 side 0
resid 1170 layer 1 side 1
resid 1171 layer 3 side 0
resid 1172 layer 1 side 0
resid 1173 layer 5 side 1
resid 1174 layer 3 side 1
resid 1175 layer 4 side 1
resid 1176 layer 4 side 1
resid 1177 layer 4 side 1
resid 1178 layer 3 side 1
resid 1179 layer 1 side 1
resid 1180 layer 5 side 1
resid 1181 layer -1 side -1
resid 1182 layer 5 side 1
resid 1183 layer -1 side -1
resid 1184 layer -1 side -1
resid 1185 layer -1 side -1
resid 1186 layer 1 side 0
resid 1187 layer 2 side 0
resid 1188 layer 2 side 0
resid 1189 layer 3 side 0
resid 1190 layer 3 side 1
resid 1191 layer 3 side 1
resid 1192 layer 4 s

In [32]:
i = 145
print('resid', i, 'layer', u.residues[i].atoms.layers[0], 'side', u.residues[i].atoms.sides[0])
print('resid', i, 'layer', 4+2-u.residues[i].atoms.layers[0], 'side', u.residues[i].atoms.sides[0])

i = 147
print('resid', i, 'layer', u.residues[i].atoms.layers[0], 'side', u.residues[i].atoms.sides[0])
print('resid', i, 'layer', 4+2-u.residues[i].atoms.layers[0], 'side', u.residues[i].atoms.sides[0])

i = 149
print('resid', i, 'layer', u.residues[i].atoms.layers[0], 'side', u.residues[i].atoms.sides[0])
print('resid', i, 'layer', 4+2-u.residues[i].atoms.layers[0], 'side', u.residues[i].atoms.sides[0])

i = 182
print('resid', i, 'layer', u.residues[i].atoms.layers[0], 'side', u.residues[i].atoms.sides[0])
print('resid', i, 'layer', 4+2-u.residues[i].atoms.layers[0], 'side', u.residues[i].atoms.sides[0])

i = 191
print('resid', i, 'layer', u.residues[i].atoms.layers[0], 'side', u.residues[i].atoms.sides[0])
print('resid', i, 'layer', 4+2-u.residues[i].atoms.layers[0], 'side', u.residues[i].atoms.sides[0])


resid 145 layer 5 side 0
resid 145 layer 1 side 0
resid 147 layer 3 side 1
resid 147 layer 3 side 1
resid 149 layer 1 side 0
resid 149 layer 5 side 0
resid 182 layer 3 side 0
resid 182 layer 3 side 0
resid 191 layer 1 side 1
resid 191 layer 5 side 1


In [ ]:
for k in range(0, nbr_layer, 1):
    upper_layer = interface.layers[0,k]
    print(upper_layer.resids)
    iii = 0
    while iii < len(upper_layer.resids):
        nbr_resid = upper_layer.resids[iii]
        print(nbr_resid)
        while nbr_resid == upper_layer.resids[iii] and iii < len(upper_layer.resids):
            iii += 1

# The original test file: 

In [7]:
directory = '/data/glebreton/Documents/Encadrement/Stage/2019-2020/Fichier_thibault/MD/2D_40/'
# load an example configuration file
u = MDAnalysis.Universe(directory + 'first_equi.data')
# initialize the interface, this has to be called only once
# before iterating over the trajectory!
interface = pytim.ITIM(u, max_layers=4)

# write a pdb with the information on the surface layers
interface.writepdb('layers.pdb',centered='middle')

# access the atoms in the layers as an MDAnalysis' AtomGroups
upper_layer = interface.layers[0,0]

print(upper_layer.resids)
print(u.residues[0].atoms.radii)
print(u.residues[1979].atoms.radii)

[   6    6    6   30   30   30   87   87   87  108  108  108  121  121
  121  142  142  142  160  160  160  197  197  197  240  240  240  274
  274  274  307  307  307  353  353  353  499  499  499  501  501  501
  593  593  593  626  626  626  697  697  697  760  760  760  806  806
  806  839  839  839  942  942  942  958  958  958 1011 1011 1011 1093
 1093 1093 1116 1116 1116 1205 1205 1205 1205 1205 1205 1207 1207 1207
 1207 1207 1207 1236 1236 1236 1236 1236 1236 1265 1265 1265 1265 1265
 1265 1271 1271 1271 1271 1271 1271 1275 1275 1275 1275 1275 1275 1324
 1324 1324 1324 1324 1324 1335 1335 1335 1335 1335 1335 1336 1336 1336
 1336 1336 1336 1352 1352 1352 1352 1352 1352 1371 1371 1371 1371 1371
 1371 1374 1374 1374 1374 1374 1374 1380 1380 1380 1380 1380 1380 1384
 1384 1384 1384 1384 1384 1386 1386 1386 1386 1386 1386 1419 1419 1419
 1419 1419 1419 1432 1432 1432 1432 1432 1432 1434 1434 1434 1434 1434
 1434 1437 1437 1437 1437 1437 1437 1443 1443 1443 1443 1443 1443 1450
 1450 

/home/glebreton/.local/lib/python3.7/site-packages/MDAnalysis/coordinates/PDB.py:1028: UserWarning: Found no information for attr: 'resnames' Using default value of 'UNK'
  "".format(attrname, default))


In [63]:
N_wat = 1050
N_meth = 1050

print((8400-3*N_wat)/6)

875.0


In [53]:
8400/(0.4*3+0.6*6)

1750*0.6

1050.0

In [ ]:
print(u.)

In [7]:
directory = '/data/glebreton/Documents/Encadrement/Stage/2019-2020/Fichier_thibault/MD/2D_40/'
# load an example configuration file
u = MDAnalysis.Universe(directory + 'first_equi.data')
#print(u.residues[0].atoms.types)
#print(u.residues[1260].atoms.types)

u.add_TopologyAttr('radii')
#print(u.residues[0].atoms.names)

for i in range(0, 1200, 1):
    #u.residues[i].atoms.names = ['O', 'H', 'H']
    u.residues[i].atoms.types = ['O', 'H', 'H']
    u.residues[i].atoms.radii = [0.8, 0.1, 0.1]
    
for i in range(1200, 2000, 1):
    #u.residues[i].atoms.names = ['O', 'H', 'C', 'H', 'H', 'H']
    u.residues[i].atoms.types = ['O', 'H', 'C', 'H', 'H', 'H']
    u.residues[i].atoms.radii = [0.4, 0.2, 1.1, 0.14, 0.15, 0.16]
    
#print(u.residues[0].atoms.types)
#print(u.residues[1260].atoms.types)
# print(u.residues[0].atoms.names)

#mydict    = {'O':1.14 , 'H':0.0 , 'C':1.5 , 'H':0.0 , 'H':1.6 , 'H':0.0}
interface = pytim.ITIM(u, max_layers=4, radii_dict=mydict, warnings=True)

#pytim.ITIM(u, radii_dict={'O':1.14})
#interface = pytim.ITIM(u, max_layers=4,  warnings=True)


print(u.residues[0].atoms.radii)
print(u.residues[1979].atoms.radii)
# print(u.residues[0].atoms.names)


NameError: name 'mydict' is not defined

In [29]:
directory = '/data/glebreton/Documents/Encadrement/Stage/2019-2020/Fichier_thibault/MD/2D_40/'
# load an example configuration file
u = MDAnalysis.Universe(directory + 'first_equi.data')
#print(u.residues[0].atoms.types)
#print(u.residues[1260].atoms.types)

u.add_TopologyAttr('names')
u.add_TopologyAttr('radii')
u.add_TopologyAttr('resnames')
print(u.atoms[0])

u.select_atoms('resid 1').residues.resnames = 'wat'
print(u.select_atoms('resid 1'))

u.residues[0].atoms.resnames = 'ok'
print(u.residues[0].atoms.resnames)


u.atoms[:].resnames = ['wat' for k in range(0, len(u.atoms[:].resnames))]

print(u.residues[0])



<Atom 1:  of type 1 of resname , resid 1 and segid SYSTEM>
<AtomGroup [<Atom 1:  of type 1 of resname wat, resid 1 and segid SYSTEM>, <Atom 2:  of type 2 of resname wat, resid 1 and segid SYSTEM>, <Atom 3:  of type 2 of resname wat, resid 1 and segid SYSTEM>]>


/home/glebreton/.local/lib/python3.7/site-packages/MDAnalysis/core/selection.py:675: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  mask = np.zeros(len(vals), dtype=np.bool)


NotImplementedError: Cannot set resnames from AtomGroup. Use 'AtomGroup.residues.resnames = '

In [36]:
directory = '/data/glebreton/Documents/Encadrement/Stage/2019-2020/Fichier_thibault/MD/2D_40/'
# load an example configuration file
u = MDAnalysis.Universe(directory + 'first_equi.data')
#print(u.residues[0].atoms.types)
#print(u.residues[1260].atoms.types)

u.add_TopologyAttr('names')
u.add_TopologyAttr('radii')
u.add_TopologyAttr('resnames')

for i in range(0, 1200, 1):
    u.residues[i].atoms.names = ['O', 'H', 'H']
    u.residues[i].atoms.types = ['O', 'H', 'H']
    u.residues[i].atoms.radii = [0.8, 0.71, 0.72]
    u.select_atoms('resid ' + str(i)).residues.resnames = 'Wat'
    
for i in range(1200, 2000, 1):
    u.residues[i].atoms.names = ['O', 'H', 'C', 'H', 'H', 'H']
    u.residues[i].atoms.types = ['O', 'H', 'C', 'H', 'H', 'H']
    u.residues[i].atoms.radii = [1.4, 1.6, 1.1, 1.41, 1.45, 1.46]
    u.select_atoms('resid ' + str(i)).residues.resnames = 'Met'

#with MDAnalysis.coordinates.LAMMPS.DATAWriter('my_topology.data') as Towrite:
#    Towrite.write(u)
print('before 1')
print(u.residues[0].atoms.radii)
print(u.residues[1979].atoms.radii)

interface = pytim.ITIM(u, max_layers=4, warnings=True)
upper_layer = interface.layers[0,1]
print(upper_layer.resids)
interface.writepdb('layers_1.pdb',centered='middle')

print('after 1')
print(u.residues[0].atoms.radii)
print(u.residues[1979].atoms.radii)

for i in range(0, 1200, 1):
    u.residues[i].atoms.names = ['O', 'H', 'H']
    u.residues[i].atoms.types = ['O', 'H', 'H']
    u.residues[i].atoms.radii = [2., 0.0, 0.0]
    
for i in range(1200, 2000, 1):
    u.residues[i].atoms.names = ['O', 'H', 'C', 'H', 'H', 'H']
    u.residues[i].atoms.types = ['O', 'H', 'C', 'H', 'H', 'H']
    u.residues[i].atoms.radii = [3.0, 0.0, 3.0, 1.5, 1.5, 1.5]

print('before 2')
print(u.residues[0].atoms.radii)
print(u.residues[1979].atoms.radii)

interface = pytim.ITIM(u, max_layers=4, warnings=True)
upper_layer = interface.layers[0,1]
print(upper_layer.resids)
interface.writepdb('layers_2.pdb',centered='middle')

print('after 2')
print(u.residues[0].atoms.radii)
print(u.residues[1979].atoms.radii)
    

/home/glebreton/.local/lib/python3.7/site-packages/MDAnalysis/core/selection.py:675: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  mask = np.zeros(len(vals), dtype=np.bool)


before 1
[0.8  0.71 0.72]
[1.4  1.6  1.1  1.41 1.45 1.46]
[  20   20   20   23   23   23   30   30   30   87   87   87   88   88
   88  116  116  116  142  142  142  160  160  160  179  179  179  184
  184  184  203  203  203  209  209  209  222  222  222  240  240  240
  245  245  245  265  265  265  268  268  268  300  300  300  345  345
  345  361  361  361  413  413  413  448  448  448  483  483  483  484
  484  484  501  501  501  523  523  523  554  554  554  593  593  593
  616  616  616  626  626  626  666  666  666  704  704  704  756  756
  756  790  790  790  842  842  842  897  897  897  900  900  900  933
  933  933  942  942  942  946  946  946  976  976  976 1013 1013 1013
 1036 1036 1036 1039 1039 1039 1067 1067 1067 1079 1079 1079 1093 1093
 1093 1095 1095 1095 1120 1120 1120 1126 1126 1126 1163 1163 1163 1183
 1183 1183 1191 1191 1191 1207 1207 1207 1207 1207 1207 1213 1213 1213
 1213 1213 1213 1215 1215 1215 1215 1215 1215 1278 1278 1278 1278 1278
 1278 1299 1299 129

In [97]:
directory = '/data/glebreton/Documents/Encadrement/Stage/2019-2020/Fichier_thibault/MD/2D_40/'
# load an example configuration file
u = MDAnalysis.Universe(directory + 'first_equi.data')
#print(u.residues[0].atoms.types)
#print(u.residues[1260].atoms.types)

u.add_TopologyAttr('names')
u.add_TopologyAttr('radii')
#print(u.residues[0].atoms.names)

for i in range(0, 1200, 1):
    u.residues[i].atoms.names = ['O', 'H', 'H']
    u.residues[i].atoms.types = ['O', 'H', 'H']
    u.residues[i].atoms.radii = [0.8, 0.71, 0.72]
    
for i in range(1200, 2000, 1):
    u.residues[i].atoms.names = ['O', 'H', 'C', 'H', 'H', 'H']
    u.residues[i].atoms.types = ['O', 'H', 'C', 'H', 'H', 'H']
    u.residues[i].atoms.radii = [1.4, 1.6, 1.1, 1.41, 1.45, 1.46]

#with MDAnalysis.coordinates.LAMMPS.DATAWriter('my_topology.data') as Towrite:
#    Towrite.write(u)

with MDAnalysis.coordinates.PQR.PQRWriter('my_topology.pqr') as Towrite:
    Towrite.write(u)


/home/glebreton/.local/lib/python3.7/site-packages/MDAnalysis/coordinates/PQR.py:294: UserWarning: Supplied AtomGroup was missing the following attributes: resnames. These will be written with default values. 
  "".format(miss=', '.join(missing_topology)))


In [9]:
import pytim
import MDAnalysis 

u = MDAnalysis.Universe('my_topology.pqr', '/data/glebreton/Documents/Encadrement/Stage/2019-2020/Fichier_thibault/MD/2D_40/first_equi.data')

print(u.residues[0].atoms.types, u.residues[0].atoms.names, u.residues[0].atoms.radii)
print(u.residues[1979].atoms.radii)

interface = pytim.ITIM(u, max_layers=4, warnings=True)

#pytim.ITIM(u, radii_dict={'O':1.14})
#interface = pytim.ITIM(u, max_layers=4,  warnings=True)


print(u.residues[0].atoms.radii)
print(u.residues[1979].atoms.radii)

['O' 'H' 'H'] ['O' 'H' 'H'] [0.80000001 0.70999998 0.72000003]
[1.39999998 1.60000002 1.10000002 1.40999997 1.45000005 1.46000004]


/home/glebreton/.local/lib/python3.7/site-packages/MDAnalysis/topology/base.py:203: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  residx = np.zeros_like(criteria[0], dtype=np.int)


[0.80000001 0.70999998 0.72000003]
[1.39999998 1.60000002 1.10000002 1.40999997 1.45000005 1.46000004]


<ResidueGroup [<Residue 1>, <Residue 2>, <Residue 3>, ..., <Residue 1998>, <Residue 1999>, <Residue 2000>]>


[1.31292702 0.         0.        ]
[1.31292702 0.         1.6805487  0.         0.         0.        ]


In [28]:
interface = pytim.ITIM(u, radii_dict={'1':1.2 , '2':0.0 , '98':1.5 , '99':0.0 , '101':1.6 , '100':0.0}, max_layers=4, warnings=True)

print(u.residues[0].atoms.radii)
print(u.residues[1979].atoms.radii)

upper_layer = interface.layers[0,0]
#print(upper_layer.resids)
interface.writepdb('layers_1.pdb',centered='middle')




[0.717 0.717 0.717]
[0.717 0.717 0.717 0.717 0.717 0.717]


/home/glebreton/.local/lib/python3.7/site-packages/MDAnalysis/coordinates/PDB.py:1028: UserWarning: Found no information for attr: 'resnames' Using default value of 'UNK'
  "".format(attrname, default))


In [27]:
interface = pytim.ITIM(u, radii_dict={'1':0 , '2':0.0 , '98':1.5 , '99':0.0 , '101':1.6 , '100':0.0}, max_layers=4, warnings=True)

upper_layer = interface.layers[0,1]
print(upper_layer.resids)
interface.writepdb('layers_2.pdb',centered='middle')

[   8    8    8   20   20   20   23   23   23   39   39   39   43   43
   43   87   87   87   88   88   88   89   89   89  110  110  110  113
  113  113  118  118  118  155  155  155  160  160  160  177  177  177
  179  179  179  184  184  184  188  188  188  209  209  209  222  222
  222  240  240  240  245  245  245  265  265  265  268  268  268  345
  345  345  361  361  361  364  364  364  382  382  382  413  413  413
  426  426  426  441  441  441  459  459  459  487  487  487  503  503
  503  505  505  505  548  548  548  551  551  551  554  554  554  616
  616  616  643  643  643  666  666  666  681  681  681  694  694  694
  704  704  704  756  756  756  815  815  815  820  820  820  825  825
  825  837  837  837  847  847  847  849  849  849  874  874  874  900
  900  900  914  914  914  933  933  933  939  939  939  944  944  944
  946  946  946  969  969  969  976  976  976 1039 1039 1039 1051 1051
 1051 1079 1079 1079 1096 1096 1096 1133 1133 1133 1141 1141 1141 1163
 1163 

/home/glebreton/.local/lib/python3.7/site-packages/MDAnalysis/coordinates/PDB.py:1028: UserWarning: Found no information for attr: 'resnames' Using default value of 'UNK'
  "".format(attrname, default))


In [43]:
gromos = pytim_data.vdwradii(G43A1_TOP)
print(gromos.keys())
gromos['O'] = 1.6


pytim.ITIM(u, radii_dict=gromos)

interface = pytim.ITIM(u, max_layers=4,  warnings=True)
#interface = pytim.ITIM(u, max_layers=4, warnings=True)

print(u.residues[0].atoms.radii)
print(u.residues[1979].atoms.radii)


dict_keys(['O', 'OM', 'OA', 'OW', 'N', 'NT', 'NL', 'NR', 'NZ', 'NE', 'C', 'CH1', 'CH2', 'CH3', 'CH4', 'CR1', 'HC', 'H', 'S', 'CU1+', 'CU2+', 'FE', 'ZN2+', 'MG2+', 'CA2+', 'P', 'AR', 'F', 'CL', 'BR', 'CMet', 'OMet', 'NA+', 'CL-', 'CChl', 'CLChl', 'HChl', 'SDmso', 'CDmso', 'ODmso', 'CCl4', 'CLCl4', 'SI', 'MNH3', 'OWT3', 'OWT4', 'MW', 'DUM', 'IW'])
[1.31292702 0.         0.        ]
[1.31292702 0.         1.6805487  0.         0.         0.        ]


['1' '2' '3']


In [ ]:
with MDAnalysis.coordinates.LAMMPS.DCDWriter(name_file_traj, n_atoms=u.atoms.n_atoms) as Towrite:
    Towrite.write(u)